version: '3'

services:
  db:
    image: mysql:5.7
    container_name: eccube_db
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - eccube-db-data:/var/lib/mysql
    ports:
      - 3306:3306

  app:
    build: .
    container_name: eccube
    ports:
      - 8080:80
    stdin_open: true
    tty: true
    depends_on:
      - db

volumes:
  eccube-db-data:
    driver: local
